config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"


  resources :home do
    collection do
      get :add_proyection
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_locale, :get_path

  def set_locale
    I18n.locale = current_user.language if current_user
    I18n.locale = params[:language]   if !current_user
  end

  def get_path
    uri = URI(request.url)
    @path = uri.path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :set_price, except: [:add_proyection]

  def index
    @title = t('home.title')
    set_application
  end

  def create

  end

  def add_proyection
    if params[:amount].to_f > 0
      # Generate proyection 12 months
      response = Proyection.generate(params)
    else
      response = {success: false, message: "The amount must be greater than 0"}
    end
    @response = response
  end

  private

    def set_price
      # Get Price BTC and ETH in Binance, Messari and Cryptomarketcap
      response = GetPriceCurrency.set_price
      @currencies_price = response[:data]
    end

    def set_application
      @set_application ||= [['Binance', 0],['Coinmarketcap', 1],['Messari', 2]]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def application(app)
    case app
    when 0
      "Binance"
    when 1
      "Coinmarketcap"
    when 2
      "Messari"
    end
  end
end

app/views/home/_add_proyection.html.haml
- id = SecureRandom.uuid.to_s[0,8]
= render partial: 'proyection', locals: {child_index: id, response: @response}

app/views/home/_proyection.html.haml
- if response[:success]
  %div.proyections{id: "close_#{child_index}"}
    
    - response[:proyections].each do |proyection|
      %div
        %strong
          %a.close{'data-id': "#{child_index}", role: "alert"} &times;
        %h1= application(proyection[:application])
        %table
          %thead
            %th= t("general.inversion")
            %th= "#{proyection[:amount]} USD / #{proyection[:interest]}%"
        %table
          %thead
            %th= proyection[:currency]
          %tbody
            %tr
              %td
                %table
                  %thead
                    %th= t('general.month')
                    %th= t('general.amount_usd')
                    %th= t('general.amount_crypto')
                  %tbody
                    - proyection[:data].each do |hi|
                      %tr
                        %td= hi[:month]
                        %td= hi[:amount_usd]
                        %td= hi[:amount_crypto]
- else
  %div.alert.alert-warning.alert-position{id: "close_#{child_index}"}
    %strong
      = response[:message]
      !
      %a.close{'data-id': "#{child_index}", role: "alert"} &times;

:javascript

  $('.close').on('click', function(){
    let id = $(this).data('id');
    $("#close_"+id).remove();
  });

app/views/home/add_proyection.js.erb
$("#proyection").prepend("<%= j(render partial: 'add_proyection')%>");

app/views/home/index.html.haml
%div.row
  %div.card
    %div.div-comp.pb-4
      %h1= t('general.information')
      %h1= t('general.price_actual')
    %div.two-div
      %div.left.form
        %div.form-group-select.pt-10
          = select_tag 'application', options_for_select(@set_application), {:include_blank => t('general.select_application'), :class => 'form-select', id: 'application'}
              
        %div.form-group
          =number_field_tag :amount,nil, placeholder: t('general.amount')

        %div.col-12.pt-10
          %button#generate.btn.btn-login{disabled: true}= t('buttons.generate')

      %div.right
        %table
          %title= t('general.price_actual')
          %thead
            %th App
            %th Currency
            %th Price
          %tbody
            - @currencies_price.each do |currency|
              %tr
                %td= currency[:application]
                %td= currency[:name]
                %td= currency[:price]
            
    %div
      #proyection

:javascript

  $("#generate").on('click', function(){
    let application = $("#application").val();
    let amount = $("#amount").val();
    let url = "#{add_proyection_home_index_url}"
    $.get( url, {application,amount} );
  })

  $("#application").on('change', function(){
    let application = $("#application").val();
    let amount = $("#amount").val();
    if((application) && (amount)){
      $("#generate").prop('disabled', false);
    }else{
      $("#generate").prop('disabled', true);
    }
  })

  $("#amount").on('change', function(){
    let application = $("#application").val();
    let amount = $("#amount").val();
    if((application) && (amount)){
      $("#generate").prop('disabled', false);
    }else{
      $("#generate").prop('disabled', true);
    }
  })

app/views/layouts/_sidebar.html.haml
%nav#sidebar
  %div.sidebar-header{align: "center"}
    %div.sidebar-arrow
      %div.logo
        = image_tag 'icon-logo.jpeg'
        %h1= current_user.name
        %h2 
          ID:
          = current_user.id

    %div.col-12.logomenu.nopadding
      %div.container
        %ul.list-unstyled.components{style: "margin-top:20px"}

          %li.only{style: "margin-top:10px;"}
            %a#Home.link-home{href: "/"}
              = image_tag 'sidebar/home.svg', class: 'sidebar-button-img' 
              %strong= t('home.title')
                    

          %li.only{style: "margin-top: auto;"}
  
          %li{style: "margin-top:10px"}
            = link_to destroy_user_session_path(), method: :delete, class: 'sidebar-button font-white', id: 'logout-button' do
              = image_tag 'sidebar/logout.png', class: 'sidebar-button-img'
              = t('sidebar.logout')

app/views/layouts/_topbar.html.haml
%div.nav
  %div.information
    %h1= @title
    %h2= @path

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title Disruptive
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %meta{name: "description", content: "Purpose Application UI is the following chapter we've finished in order to create a complete and robust solution next to the already known Purpose Website UI."}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
      
  %body
    %div.main-container.mx-auto
      %div.main-grid
        %nav.container-nav
          = render partial: 'layouts/sidebar'
        %div.background-topbar
          = render partial: 'layouts/topbar'
          %div#notifications.mt-4
            = render partial: 'notifications/flash'
          %div.pt-10
            = yield
    = render partial: '/modals/general'

app/views/layouts/devise.html.haml
%html
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %meta{name: "description", content: "Purpose Application UI is the following chapter we've finished in order to create a complete and robust solution next to the already known Purpose Website UI."}
    %meta{name: "author", content: "Webpixels"}
    %link{rel: "icon", href: "#", type: "image/png"}
    %title SuperStem
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body.body-login
    %div.container
      %div.authentication
        %div#notifications.mt-4
          = render partial: 'notifications/flash'
        = yield

app/views/modals/_general.html.haml
%div#modal.modal-wrapper
  %div.modal-body.card
    %div.modal-header
      %h2#text-head.heading Title
      %a.close{href: "#!", role: "button", "aria-label": "close this modal"}
        %svg{viewBox: "0 0 24 24"}
          %path{d: "M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"}
    %p#text-body Text body
  %a.outside-trigger{href: "#!"}

app/views/notifications/_flash.html.haml
- if flash[:alert]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:alert].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close", role: "alert"} &times;

- if flash[:danger]
  %div.alert.alert-danger.alert-position
    %strong
      = flash[:danger].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close", role: "alert"} &times;

- if flash[:notice]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:notice].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close", role: "alert"} &times;

- if flash[:successfully]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:successfully].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close", role: "alert"} &times;

- if flash[:warning]
  %div.alert.alert-warning.alert-position
    %strong
      = flash[:warning].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close", role: "alert"} &times;